# =====================================================================
# PDM I2S 麦克风模块 CMakeLists.txt
# =====================================================================
# 源文件: audio_app.c
# 依赖: log (日志), driver (I2S PDM 驱动)
# =====================================================================

idf_component_register(
    SRCS "audio_app.c"
    INCLUDE_DIRS "."         # 头文件在当前目录
    REQUIRES log driver      # 依赖日志和底层硬件驱动(driver)
)
