# -*- coding: utf-8 -*-
"""
@file convert_dat.py
@brief TTS 语音模型二进制转 C 数组工具

功能：
    将 ESP-TTS 的二进制语音模型文件 (.dat) 转换为 C 语言源文件 (.c)，
    生成一个 const uint8_t 数组，可以直接编译进固件。

用途：
    当无法从 SD 卡加载模型时，可以使用编译时嵌入的模型作为备选。

输入: components/tts_app/esp_tts_voice_data_xiaole.dat (2.9MB 二进制)
输出: components/tts_app/voice_data.c (244,842 行 C 源码)

使用方法:
    python convert_dat.py

生成的 C 数组:
    const uint8_t esp_tts_voice_data_xiaole_dat_start[] = {
        0x01, 0x02, 0x03, ...
    };
"""

import os

# 配置路径
input_file = "components/tts_app/esp_tts_voice_data_xiaole.dat"
output_file = "components/tts_app/voice_data.c"

def convert():
    """执行二进制到 C 数组的转换"""

    # 检查输入文件是否存在
    if not os.path.exists(input_file):
        print(f"Error: Cannot find {input_file}")
        return

    # 读取二进制文件
    print("Reading binary file...")
    with open(input_file, "rb") as f:
        data = f.read()

    # 转换为 C 数组
    print(f"Converting {len(data)} bytes to C array...")
    with open(output_file, "w") as f:
        # 文件头注释
        f.write('// Auto-generated voice data. Do not edit.\n')
        f.write('// Generated by convert_dat.py\n')
        f.write('#include <stdint.h>\n\n')

        # 数组声明
        f.write('const uint8_t esp_tts_voice_data_xiaole_dat_start[] = {\n')

        # 每行写入 12 字节的十六进制数据
        for i in range(0, len(data), 12):
            chunk = data[i:i+12]
            hex_data = ", ".join([f"0x{b:02x}" for b in chunk])
            f.write(f"    {hex_data},\n")

        f.write("};\n")
        print(f"Success! Generated {output_file}")

if __name__ == "__main__":
    convert()
