# =====================================================================
# I2S 扬声器模块 CMakeLists.txt
# =====================================================================
# 源文件: speaker_app.c
# 依赖: log (日志), driver (I2S STD 驱动)
# =====================================================================

idf_component_register(
    SRCS "speaker_app.c"
    INCLUDE_DIRS "."
    REQUIRES log esp_driver_i2s
)
